### ISSUE TITLE
Board 25 LOS produces unexpected result.

### ISSUE THREAD

**Issue by jrvjrv** [vasl-developers/vasl#1799] opened 2024-08-05 04:07 UTC
I traced LOS from 25r1 to 25v6. The initial elevation in 25r1 is level -1, and of course the LOS is blocked. I then raised the 25r1 end of the LOS to level zero using ctrl-up-arrow. I expected to have to raise the 25r1 end to virtual level one, but unexpectedly vasl reports the LOS from 25r1(L0) to 25V6(L1) to be clear despite going through the level one hill in 25u5. I use red thread for clear LOS and blue thread for blocked LOS.
![los-board-25-unexpected-result](https://github.com/user-attachments/assets/eb21c3ab-7ca5-4093-832a-dfa79d381bfe)

**Comment by jrvjrv** [comment] 2024-08-05 04:23
VASSAL 3.7.13, vasl 6.6.8, os linux

**Comment by jrvjrv** [comment] 2024-08-05 20:08
Your comment made me test it the other way, i.e. tracing LOS from 25v6 to 25r1 and raising the "to" end using up-arrow. It does the same thing. I doubt it is significant but I had to try it out.

**Comment by geezer09** [comment] 2024-10-19 07:23
A fix to issue #1598 introduced this bug I believe. The problematic lines are 1272-1281 in Map.java

            // code to fix vertex los
            int vertexadj = 0;
            if (!source.equals(sourceHex.getCenterLocation()) && sourceHex.isDepressionTerrain()){
                vertexadj =1;
            }
            sourceElevation = sourceHex.getBaseHeight() + source.getBaseHeight() + vertexadj;
            if (!target.equals(targetHex.getCenterLocation()) && targetHex.isDepressionTerrain()){
                vertexadj=1;
            }
            targetElevation = targetHex.getBaseHeight() + target.getBaseHeight() + vertexadj;

Doug, I think you commited those lines and I might need you help to fix this issue. This code adds a level to the R1 hex when checking LOS in the situation mentioned by jrvjrv, but only when not at level -1.  I managed to fix the bug by changing both of the conditionals to:

            if (!source.isCenterLocation() && sourceHex.isDepressionTerrain()) 

and 

            if (!target.isCenterLocation() && targetHex.isDepressionTerrain())

but I am not quite sure why this vertexadj is necessary in the first place so I thought I'd check before maybe just replacing one bug by another.

**Comment by derimmer** [comment] 2024-10-20 01:51
@geezer Did you check to see if your changes here re-enabled the bug in #1598? 

Clearly my #1598 changes fixed one bug but created another, which you have attempted to fix. 

I will have to go back and look at  this and 1598 in some detail which will take me a few days.

I am surprised that my changes (if (!source.equals(sourceHex.getCenterLocation()) and the same for target) produced a different result than your code (if (!source.isCenterLocation()). I would have expected them to return the same boolean value. I will have to look at the two methods and check. Sometimes ".equals" does not perform as I expect it to - my lack of understanding not a problem with the function. 

I will get back to you as soon as I can. 

The reason for the vertexadj is that the LOSData is not always correct at hex vertices involving a crest line. Even though visually a vertex may appear to be at a lower level, LOS drawn to that vertex is, according to the rules, drawn to the higher level, while los drawn along a hexside containing that vertex is treated as being entirely at the lower level. VASL's LOSData does not store two elevation values for the vertex pixel so we have to code  an adjustment. I am just not doing it correctly. First glance I think the problem is more with the DepressionTerrain() test but I will look further.

**Comment by geezer09** [comment] 2024-10-20 20:48
My understanding of what is happening is that !source.equals(sourceHex.getCenterLocation() and  !source.isCenterLocation() will not always return the same results. The getCenterLocation() should probably only ever return one location per hex, whereas a hex can contain multiple center locations. In this particular case, the getCenterLocation() returns the location under the bridge in the gully, which is not equal to the location on the bridge in the same hex, although both are in the center of the same hex. 

It seems like the #1598 issue does not involve depression terrain. (I used to play ASL quite a bit and know the rules inside out but it's been a few years now so I definately might be forgetting something). Did you add some other bits of code somewhere that fixed that vertex los issue which then needed a little additional fix to get LOS to gully vertices to work? That kind of makes sense and would probably work in most cases, except if you were drawing LOS to a depression hex center location that was not IN that depression. 

Another question/comment. In your vertexadj code it seems like if you set the vertexadj value to 1 in the source hex, the target hex will get that adjustment as well, regardless of it's location. That seems like a bug to me.

**Closed** 2024-11-02 20:24 UTC
Labels: bug, 2 - Code
