### ISSUE TITLE
Problem with PBEM .vlogs: "ghost" moves retained

### ISSUE THREAD

**Issue by davidsullivan317** [vasl-developers/vasl#69] opened 2014-03-28 04:14 UTC
I'm experiencing some pretty weird behaviour in my current PBEM game, and I don't know if it is a user error or what. Basically, I'm getting these logs back from my opponent where he's responding to moves that I didn't do. Or rather, I did them several logs ago, but not in the one I just sent him. 

For instance, I'll have some logs like this:

001 I'll send a log where I move a HS into a concealed stack, then move a full squad. 
002 My opponent sends me back the log when the HS gets bumped, because the concealed stack contains a real unit.
003 I perform a series of different moves, not moving the same squad as in 001, because, well, it would get blown away by the enemy unit revealed in 001.
004 My opponent sends me back a log in which the full squad movement in 001 happens, and none of my 003 moves.

What's going on here? I've never seen this before, at all; my opponent says that there is a problem with starting a new log file right when you open up the previous log; but that's how I've always done it, creating nested logs.

Also:
We had some similar effects, not identical, but close; in .vlog to .vsav in our KGP CG3 early on while playing MPhs via VASL / Skype and PBEMing the rest of the turns. We quickly discovered that the "Load Continuation" tool in the File Drop down menu isn't programmed army - style ( Be all you can be); and in fact going from 'vlog to 'vsav; or from 'vlog to 'vlog while synced in VASL server was the culprit, thought no clue at all why it should be. Are you or your opponent using the Load Continuation instead of the Load Game? In our case, doing so meant units that had been removed would magically re- appear on board where they died up to a full game turn previously.

**Comment by mistertakai** [comment] 2016-03-07 19:32
I found a similar problem, not exactly the same. In this log, an HS is moved, but it moves only in the log. Both players use the same version of VASSAL 3.2.14 and VASL 6.3.1.

[HS32-001r.vlog.zip](https://github.com/vasl-developers/vasl/files/161963/HS32-001r.vlog.zip)

Despite having found a "ghost" error, as I'm the only reporter since Dec 2014, I propose to close this bug as "not reproducible".

**Comment by davidsullivan317** [comment] 2016-03-07 22:08
works for me

**Closed** 2016-03-07 22:09 UTC
Labels: 2 - Code, bug
