### ISSUE TITLE
board6b does not play well with overlapping overlays

### ISSUE THREAD

**Issue by jrvjrv** [vasl-developers/vasl#416] opened 2017-05-15 16:58 UTC
Construct a map by adding rows BFPE, BFPD, BFPDW2a, BFPDW2b, BFPDW6a, and BFPDW6b*. Add overlay X13 on E/m10-m11, D/m10-m11, 2a/m10-m11, 2b/m20-m21, and 6a/m10-m11. All the overlap overlays are correctly drawn except the one put on 6a. The one put on 6a shows only the half of the overlay on board 6a; the part that should be on 6b is not visible.**

*It is not necessary to add any boards but 6a & 6b. I added more to verify that other boards worked as I expected.

**I assume this is a problem with z-order, but I have not looked at the code.

**Comment by derimmer** [comment] 2017-11-09 13:16
In addition, you cannot add overlays to board 7b using the traditional Add Overlay tool as part of board selection. The draggable overlay extension does work, however, the overlays are not placed perfectly on board 7b; they seem to be low by one or two pixels. This may have to do with the board itself.

**Comment by derimmer** [comment] 2018-01-20 04:03
I believe that the overlay problem was caused by the use of the BFP a and b versions together where they form one board with rows 0-20. I discovered this while working on some other LOS issues and this should now be fixed. It will be included in VASL-6.4.2.

**Closed by derimmer** 2018-01-20 04:03 UTC
Labels: 0 - Boards, 2 - Code, bug
