### ISSUE TITLE
Support SVG format for counters

### ISSUE THREAD

**Issue by jvarsoke** [vasl-developers/vasl#218] opened 2015-04-17 14:52 UTC
SVG, a cleaner and scalable image format.

**Comment by uckelman** [comment] 2015-04-17 15:12
VASSAL already supports SVG. It has since 3.0.0, from 2007. What, specifically, is missing?

**Comment by jvarsoke** [comment] 2015-04-17 15:25
Okay.  So how would one add SVG based counters into VASL?  Or, replace the OBs with SVG counters?

For context: http://forums.gamesquad.com/showthread.php?122123-Kickstarter-campaign-for-custom-counters&p=1746764#post1746764

**Comment by uckelman** [comment] 2015-04-17 16:25
You could do that the same way you'd add any images---either via VASSAL's editor or by editing the buildFile, if you're adventurous.

**Comment by davidsullivan317** [comment] 2015-04-17 16:25
See my post in that thread. It's not support for SVG that's lacking but the army that would be needed to convert all the images to SVG format. 

Joel - do you know of a module that uses SVG images for counters and allows the counters to be rotated? SVG images look great in VASL until they are rotated. I wanted to see if other modules exhibit the same behavior and if not what we might be doing wrong (e.g. probably rotating after rendering)

**Comment by uckelman** [comment] 2015-04-17 16:38
> It's not support for SVG that's lacking but the army that would be needed to convert all the images to SVG format.

I'm aware of that---I'm just addressing the question asked. (The reason I'm aware of the magnitude of the job is that I created the module for The Longest Day, which uses SVG for all the pieces. It has circa 6000 unique piece faces...)

> I wanted to see if other modules exhibit the same behavior and if not what we might be doing wrong (e.g. probably rotating after rendering)

What precisely looks bad after rotation? Is it the line art? the text?

**Comment by davidsullivan317** [comment] 2015-04-17 16:42
Here's an example of how an SVG counter looks before (top) and after (bottom) being rotated: 
![capture](https://cloud.githubusercontent.com/assets/5281926/7206421/ca2af436-e4f6-11e4-9196-ded65a764208.PNG)

**Comment by mistertakai** [comment] 2015-04-17 17:09
The top counter does look incredibly well.

**Comment by uckelman** [comment] 2015-04-17 17:53
May I have the SVG for that?

**Comment by BigAl737** [comment] 2015-04-23 06:29
You can get the SVG here:
https://www.dropbox.com/s/d0l6c8ii4zf2tyi/sdkfz104L-3b.svg?dl=0

I've also created a VASSAL module which tests how rotations are drawn. You can get it here:
https://www.dropbox.com/s/30l5cf8o2cyzqy6/SVG_Rotate_Test.vmod?dl=0

One piece uses the vassal CAN ROTATE trait to draw the rotations. The other piece uses the LAYER trait with 6 svg images to draw the rotations.
 
I set up map zoom levels up to 5x.
 
It’d be great if VASSAL would not pixelize before rotating. The LAYER method looks better but since it takes 6 svgs for each counter, takes more time to create and makes for a bigger VASL module size.

**Comment by davidsullivan317** [comment] 2015-04-23 14:15
Note that these SVG image files are orders of magnitude (10x - 40x) bigger than the gif files. If we can't make them smaller this might be a deal-breaker as the module will bloat to hundreds of MB (or GB) even if used sparingly. 6 images at 150kb/image = 1MB for one vehicle and we have 1000s.

**Comment by jvarsoke** [comment] 2015-04-23 14:43
I think it might be a wonderful module to make available for those of us who think disk is cheap and don't mind half our drive consumed by SVG images.  I'll ask Aaron how much disk all the SVGs take up for all the OBs he has available in his color-counter project.

Of course, disk is one thing, if the SVGs take up that much space in memory, it might not be possible to play a scenario with a large OB.

**Comment by davidsullivan317** [comment] 2015-04-23 15:21
They should be about the same size in memory, as everything is really a bit map once rendered, so that would not be an issue.

**Comment by uckelman** [comment] 2015-04-23 16:01
Guys, give me a chance to look into exactly what's going on here before making any decisions. I should be able to check on this while on the train on Friday.

**Comment by uckelman** [comment] 2015-04-23 16:20
I would not worry about file size here. Firstly, at 150KB per, 5000 such images use only 833MB. That's not all that large these days. Secondly, you should be able to get the average size down to way, way less than 150KB per by creating a library file containing reusable design elements, which are referenced by `<use>` from within individual SVG images. Everything except the vehicle image could live in that library file. That means instead of having a thousand copies of the fast traversal circle, the large and unarmored target starts, the outlines for all the letters, numbers, and punctuation, etc.---those things occur _once_ in your library file. That ought to make a significant difference in both file size _and_ maintainability.

None of this will make any difference for the amount of memory used---that depends only on the dimensions of the _rendered_ bitmap.

**Comment by jvarsoke** [comment] 2015-04-23 16:45
Maybe this is OBE, but I just confirmed with Aaron (who apparently goes by Alan), that the total OB he offers is about 0.9Gig.  Of course, that doesn't include info counters etc. 

I'd welcome committing a Gig of my harddrive to have beautiful scaleable images. ;)

**Comment by BigAl737** [comment] 2015-04-24 03:34
I added an Italian Semovente counter I made to the rotation test vmod. If you zoom in you can read the AFV name. I'm liking SVG. I am really hoping that there is a way to get vassal to rotate without pixelizing.

I like Joel's idea for a library file. Don't know how to do it but I like it.

https://www.dropbox.com/s/30l5cf8o2cyzqy6/SVG_Rotate_Test.vmod?dl=0

**Comment by uckelman** [comment] 2015-04-24 12:51
I know what the problem is now. VASSAL.counters.FreeRotator has to use GamePieceOp for getting the image of what it wraps. Calls to Op.rotateScale() check whether the ImageOp passed in is also an SVGOp, and has SVGRenderer rerender the SVG with the correct scale and angle if so. The problem is that none of the GamePieceOps which reach FreeRotator are also instances of SVGOp, so when you rotate an SVG image, what happens is that it's rendered orthogonally first and then rotated _as a bitmap_.

That's not what is supposed to happen. It's an oversight that the GamePieceOps wrapping SVG which FreeRotator has are not also SVGOps. I'll see about fixing this, but I might not get to it until later next week.

**Comment by FredKors** [comment] 2015-04-25 21:43
Beautiful! If even the maps were SVGs...

**Comment by uckelman** [comment] 2015-04-28 19:35
I've taken a closer look at the source and see no easy way to make this work in V3.2. `FreeRotator` (which provides the "Can Rotate" trait) has to be able to rotate _whatever_ it wraps. It wouldn't be hard to make a `GamePieceOp` which also implements `SVGOp`, and we could get better non-orthogonal SVG rendering that way for the case where "Can Rotate" is the next trait outward from "Basic Piece". But that's not what you have in VASL. Your "Can Rotate" is pretty far separated from "Basic Piece". To improve SVG rendering for you, we'd have to add support for delaying the rendering of SVG to all of the intervening traits as well.

It would be an _enormous_ amount of work to retrofit V3.2 for this---you'd practically have to rewrite the whole graphics rendering system. VASSAL 4 will have end-to-end SVG rendering by design. I think I would take less time to give you a usable V4 demo which can do this than it would to modify V3.2 to do it.

So, don't give up on SVG pieces (and maps). I _strongly_ encourage that you switch to them for V4, but I can't justify investing the time in fixing this problem for V3.2.

**Comment by BigAl737** [comment] 2015-04-29 18:09
Thanks Joel! I eagerly await version 4. Until then I think we can focus on converting non-rotating counters and getting vehicle art ready to go. I wish I was a programmer to help you with VASSAL 4 (if you wanted it) but I'd welcome the opportunity to test the V4 demo when you get it done.

**Comment by davidsullivan317** [comment] 2015-06-13 15:19
Not VASL so closing

**Closed by davidsullivan317** 2015-06-13 15:19 UTC
Labels: 1 - Counters, enhancement
