### ISSUE TITLE
VASL 6.3 release discussion 

### ISSUE THREAD

**Issue by davidsullivan317** [vasl-developers/vasl#208] opened 2015-03-27 20:57 UTC
I hadn't planned on releasing VASL 6.3 so soon, but Jeff has the HP counters ready and I think it's worth pushing out sooner rather than later. I know I'd like to try an HP scenario on VASL!

I have two large/complicated changes in this release and would appreciate it if people could commit an hour or two to testing them:

Automated board updates #205
Sunset the old board SSR text files #117

Also, please review the HP if you can.

You can find the initial build here: https://www.dropbox.com/s/qz8wwsf0thfkgis/vasl-6.3.0-Snapshot-20150327.vmod?dl=0

**Comment by zgrose** [comment] 2015-03-28 17:09
Re: the Finnish counters: Are we going with counter scans as an interim get-it-out the door solution or is the preferred long term solution for counters?

![screen shot 2015-03-28 at 10 09 00 am](https://cloud.githubusercontent.com/assets/5044847/6881966/7ce1f8f6-d532-11e4-8f16-8ec40f8be6f0.png)

**Comment by mistertakai** [comment] 2015-03-28 17:45
Ask MMP to donate counter graphics to VASL?

**Comment by mistertakai** [comment] 2015-03-28 17:55
More HP counter samples:

![image](https://cloud.githubusercontent.com/assets/3066447/6882159/006b1736-d57c-11e4-8487-79c873490008.png)

**Comment by davidsullivan317** [comment] 2015-03-31 16:16
All changes to date have been incorporated in this build:
https://www.dropbox.com/s/8up2799llacp1rm/vasl-6.3.0-Snapshot-20150331.vmod?dl=0

IMPORTANT - please make any future changes to this module file.

**Comment by Wargamerx** [comment] 2015-04-01 11:50
Doesn't help. The existing VASL counters are redrawn. The scans I got looked great at 300 pixels per inch, the problem is they turn to crap when you reduce it to 96 ppi. A 60 by 60 image isn't really sufficient to store the art work and data on a 5/8" counter.

**Comment by uckelman** [comment] 2015-04-01 11:52
SVG is the best long-term solution.

**Comment by zgrose** [comment] 2015-04-01 19:16
Seems like something we get around to when we get rotatable and scalable boards in VASSAL 4? :D

**Comment by davidsullivan317** [comment] 2015-04-05 13:46
Any reason not to release the latest build for testing? We have a couple of small changes left but both are small and can come later. 

Anyone want to look #211?

**Comment by mistertakai** [comment] 2015-04-05 17:23
MMP has replied and they are unable to donate the graphics to us as they are bound by contract to Hasbro.

**Comment by bkemp01** [comment] 2015-04-06 02:18
I think the key is to use the scan for the artwork only and create the data by hand. There used to be PSD files that had layers to produce the data and you would just add the graphic as another layer.






From: Wargamerx
Sent: ‎Wednesday‎, ‎April‎ ‎1‎, ‎2015 ‎7‎:‎50‎ ‎AM
To: vasl-developers/vasl




Doesn't help. The existing VASL counters are redrawn. The scans I got looked great at 300 pixels per inch, the problem is they turn to crap when you reduce it to 96 ppi. A 60 by 60 image isn't really sufficient to store the art work and data on a 5/8" counter.

**Comment by davidsullivan317** [comment] 2015-09-12 13:39
I'm finding myself with some free time on my hands this fall, so I'm going to jump start the VASL 6.3 release. 

If you have issues you want included please tag them as such. If you'd like to work on an issue please assign it to yourself. 

Freddy/Sam/Zoltan - let me know if you're available to help with the coding.

**Comment by styson** [comment] 2015-09-14 14:56
I should have some time freeing up this fall as well.

**Comment by davidsullivan317** [comment] 2015-10-20 02:10
I'm clipping through my open issues and Carl is plowing through the HP counter testing. I'm hoping to have a test build of 6.3 available to the unwashed masses in a week or two. 

If there's anything you want to see included in the release consider this last call.

**Comment by BigAl737** [comment] 2015-10-20 04:08
Hi David,

Great job and thanks for your untiring efforts!

I will be getting back into map elf work when time permits which should be soon.

I have to confess I’ve recently been enjoying using my free time to play ASL :-)

I would like to see all counters be able to be labelled. If that’s too big a task, then how about starting with the fire lane counters?

Al

**Comment by Taschenschieber** [comment] 2015-10-22 14:00
I hope to get #236 done until them, but am not sure I get the configuration thing to work in time. Aside from that, it's pull-ready.

**Comment by davidsullivan317** [comment] 2015-10-22 21:27
@Taschenschieber  I believe I merged your branch already. 

@BigAl737 Labeling everything shouldn't be that hard - you'll have to find the minimal set of prototypes and add labeling to those. Testing will be the hard part.

**Comment by Taschenschieber** [comment] 2015-10-23 23:31
@davidsullivan317 You did some time ago, but I've added some more stuff since then. I'll add a new pull request once I'm done.

**Comment by BigAl737** [comment] 2015-10-26 01:13
I’ve updated the VASL files for bd 3 and 19 to include SSOs for OB3 Brasche Encounter and J44 Audacity!

I’m a doofus at git hub. How should I submit these for uploading?

Thanks.

Al

**Comment by BigAl737** [comment] 2015-10-26 01:13
I can do that I think. How much time do I have?

Al

**Comment by davidsullivan317** [comment] 2015-10-26 03:28
There's no rush. If you send me the files I can upload them to Github for you.  -Sully

**Comment by davidsullivan317** [comment] 2015-11-06 02:03
I think that's everything for 6.3. I've created a test build here: https://www.dropbox.com/s/6h0p6716xnx3ts9/vasl-6.3.0-beta1.vmod?dl=0

Please double check your changes and let me know if I should wait to release or not. I'll shoot for this weekend unless I hear otherwise.

**Comment by BigAl737** [comment] 2015-11-06 03:28
Hi David,

I haven’t had a chance to add a label option to RFP markers. I should get this done this weekend if that’s not too late.

Al

**Comment by davidsullivan317** [comment] 2015-11-06 08:42
Sure - no problem. Just use the beta1 module linked above to make your changes.

**Comment by derimmer** [comment] 2015-11-07 13:57
All looked good for my stuff.

**Comment by wintrymix** [comment] 2015-11-08 00:57
So I see three new items that will be visible to the player that would need to be listed in the readme:
* Updated Finnish counterset (HP counters)
* Automatic board updates
* Additional reminders for special dice rolls (DRs)
 * HoB
 * Field Promotion
 * Unlikely Hit/Unlikely Kill 
 * Dud 
 * Malf
 * Multiple Hits
 * Cower
 * Casualty MC
 * Fate
 * Booby Traps
 * Hull/Turret Hit

What does the user have to do to make the map updates happen?  The issue doesn't describe how to make it work.

Is anything missing from the list of special dice rolls?

Are any of the special dice rolls configurable?

**Comment by wintrymix** [comment] 2015-11-08 01:17
I did some testing for the special dice rolls:

Special Roll | Conditions | Result
------------ | ---------- | ------
HoB | MC snakes, Rally snakes | pass both
Field Promotion | Rally snakes, CC snakes | pass both
Unlikely Hit | TH snakes | pass
Unlikely Kill | IFT snakes, CC Snakes | IFT snakes pass, CC snakes fail
Dud | TK boxcars | pass
Malf | IFT boxcars, 11, 10; TH boxcars, 11, 10, 9 | all fail 
Multiple Hits | doubles TH | pass
Cower | doubles on IFT | pass
Casualty MC | boxcars on MC | pass
Fate | Boxcars on Rally | pass
Booby Traps | Boxcars on TC | fail
Hull/Turret Hit | wdr/cdr | pass

**Comment by davidsullivan317** [comment] 2015-11-08 01:33
Here is the release summary I'm including in the release announcement:

Hakkaa Päälle Counters!
-You've waited long enough, but now it's time to slap on some virtual skis and tackle that electronic Motti. Enjoy!

Automatic board synchronization!
-Have an out-of-date copy of a board? No worries - VASL now grabs the latest board from the repository when you create or open a game. Missing a board altogether? Not a problem - the missing board will be copied to your board directory and you're off and running. 
-
Other enhancements:
-More reminders for special die rolls were added to the QC dice buttons. Unlikely hits, Multiple hits, turret vs. hull... stuff like that.
-Partial support for LOS checking when using overlays was added. LOS checking is only disabled if it touches the overlay outline. 
-Mark Unmoved button was moved to the left so it won't "disappear" on smaller screens.
-Free-French support weapons were copied to the British counter mix.
-Moving HIP units no longer reports "? -> ?" to the chatter.
-Scenario-specific overlays were added to boards 3 and 19 for scenarios J44 and OB3.
-Gutted factories, ground snow, and a non-rubbled Chemist shop were added to the RBv2 board. In addition some missing sewers were found and returned to their rightful location. 
-HIP option was added to all counters. You never know...
-The code that handles the SSR terrain changes was completely gutted "under the covers." Keep your eyes open for any problems when applying terrain changes, cropping, etc. 
-
Bug fixes:
-The "disappearing" counters and stacks bug should finally (!) be fixed.
-Snap points were missing on deluxe boards.
-LOS checks no longer lose the chatter focus when stepping through a log file.
-Hungarian Vehicle Crews had the wrong morale.
-"Crags to palmtrees" SSR transformation was not working on some boards.
-"Woods-Roads - Fill in with woods" SSR transformation was not working on some boards.
-Bocage incorrectly blocked LOS to some higher elevations. 
-Japanese crews and SMCs were missing Prep Fire and First Fire options. 
-Smoke exponents on Chinese Type 89 MTR were wrong.
-The labels on the CA counters were in the wrong position.
-Bad hex sizes on BFP boards bug were fixed.
-Blank boards (all white boards with a hex grid) are available. They're great for setups and when you need a little elbow room on the board.

**Comment by Taschenschieber** [comment] 2015-11-08 20:49
I didn't implement Malf and Booby Traps on purpose - malf because it's too variable, booby traps because frankly I think they're too much of a corner case. CC Unlikely Kill is my bad, will try and fix tomorrow. My rule book is several hundred kilometers away, so I'd appreciate if one of you could look up the paragraph number. 

If you think malf and BTs should be implemented, I can do that, too.

For reference, you can choose between four levels of notifications - none, Snipers only (mirrors behaviour in 6.2), Starter Kit, Full ASL.

**Comment by Taschenschieber** [comment] 2015-11-08 20:51
Also, aren't coloured counters in collapsed stacks new as well? I guess they should be mentioned.

**Comment by wintrymix** [comment] 2015-11-08 23:26
CC Unlikely Kill is A11.501:
"An Original 2 CC DR always results in a chance of success for the attacket even if a CC DRM or small CCV otherwise makes success impossible.  Whenever the attacker makes an Original 2 DR, he may roll a third die.  IF the subsequent dr is a 1, the vehicle is a buring wreck; if a 2 it is eliminated, if a 3 it is immobilized; otherwise there is no effect.  However, regardless of the subsequent dr, if the Original 2 DR would have resulted in an elimination or Immobilization that result still occurs, unless cancelled by an elimination or burning wreck from the subsequent dr.:

**Comment by wintrymix** [comment] 2015-11-08 23:27
Where is the level of notification configured?  I looked at the Preferences and didn't find it.  Is it somewhere else?

**Comment by wintrymix** [comment] 2015-11-08 23:42
Understood why you didn't implement Malf and BT.  I'm fine with deferring the implementation of these notifications to a future release.  

Agreed BT are a rare case (not sure I would call them a corner case, since they are a rule, just an infrequently used rule).  Moreover, since the rules allow three levels, the level should probably be configurable.  Perhaps that could be implemented in a future release.

Malf might be considered for a future implementation as well.  Could the code being used to detect the maps being used be adapted to detect whether a counter is on the board that has a lower breakdown number (or Circled B#)?  That would require no intervention from the user.  Just a thought. Not saying it's not worth doing if automatic detection is not feasible or is excessive work.  In that case, manual configuration is fine.  I think these enhancements would add value.

**Comment by BigAl737** [comment] 2015-11-09 00:13
How about adding an additional dust die option (F11.7) to IFT and TH DRs? Something you could click on and off in preferences. I would really appreciate this option.

Less appealing to me but maybe worth consideration would be referencing molotov effects (A22.6111) to the IFT colored dr and TH colored dr for molotov projectors (C13.57).

Allan

**Comment by wintrymix** [comment] 2015-11-09 01:19
Those sound like different features. We should probably take them to a different thread.

**Comment by Taschenschieber** [comment] 2015-11-09 15:21
Right.

Making malf dependent on which counters are on board sounds like an interesting idea, but I'm not sure if it's worth the effort. It's definitely out of scope for 6.3, so let's take it to a new ticket for the 6.4 milestone.

**Comment by wintrymix** [comment] 2015-11-09 22:23
Is there a 6.4 or general future features discussion thread somewhere?  We can continue the discussion there.

**Comment by davidsullivan317** [comment] 2015-11-10 17:44
Go ahead and create one

**Comment by davidsullivan317** [comment] 2015-11-15 17:32
Hey all - the (hopefully) production build of VASL 6.3 is here: https://www.dropbox.com/s/5694cvjld6lkgge/vasl-6.3.0.vmod?dl=0

Please give it a test drive and make sure everything looks. If so I'd ask Sam to put it up on vasl.info for release. Sam - the release description is above... just one more addition: Label option has been added to all counters. 

Thanks all for your help making this happen!

**Comment by zgrose** [comment] 2015-11-15 19:53
Did overlay updating mentioned in #205 make it into this build? It appears not.

**Comment by davidsullivan317** [comment] 2015-11-15 22:25
No - just for boards for now. I'll add an issue for overlays.

**Comment by davidsullivan317** [comment] 2015-11-22 16:08
The latest build of 6.3 is here: please review your changes to make sure they look good. 
https://www.dropbox.com/s/esa8t4epdb46q7d/vasl-6.3.0-20151121.vmod?dl=0

If there are no issues I'll "release" it for testing.

**Comment by mistertakai** [comment] 2015-11-22 18:17
I suggest to call it 6.3.1 as people have already read the announcement on the VASL homepage and downloaded 3.0, to better distinguish the two versions. There was a FB post about it.

**Comment by uckelman** [comment] 2015-11-22 18:45
Yes, this. ^^^^

Don't reuse release numbers.

**Comment by davidsullivan317** [comment] 2015-11-23 03:49
The build in my last post was bad. Please use this one:
https://www.dropbox.com/s/wzzgex7g0z9al8u/vasl-6.3.0-20151122.vmod?dl=0

Also, if you make any other changes for 6.3 please use the 6.3 branch. I'll merge everything into develop after we're done.

**Comment by derimmer** [comment] 2015-11-24 00:22
My stuff seemed to work fine with one exception: 

 

If you set up a board with overlays and open the scenario and then go back to the board selection process (using Pick New Boards for this scenario), the overlays remain in memory even if they are deleted or change position (they will show up in the new and old positions). There is also a similar problem if you close a scenario without saving it and create another immediately thereafter: overlays in the first scenario are retained while the second ones are not added.

 

I will start to investigate causality but it seems like a collection is not being disposed properly.

 

Doug

**Comment by derimmer** [comment] 2015-11-25 20:51
Sully

 

I did not use the 6.3 branch when I fixed the LOS Overlays bug. Sorry about that, completely forgot! 

 

When I created a push request it let me merge the change into develop which I did.

 

Doug

**Comment by FredKors** [comment] 2015-11-25 23:07
Hello!

I’ve just noticed that the CC/Melee counters lost the context menu item that alllow to change them to the Hand-to-Hand version (probably it has been overwrite by the HIP menu command).

Freddy

**Comment by davidsullivan317** [comment] 2016-02-05 22:08
So, I have to admit I've been slacking of late. My intent was to get 6.3 out the door months ago, but obviously that didn't happen. Everything is ready to go; the code is in the 6.3 branch: https://github.com/vasl-developers/vasl/tree/release-6.3.0

I'm going out of town for a couple of weeks. If someone wanted to push the release out the door in my absence please feel free to do so. What's left to do is:

* Build module from 6.3 branch. Let call it 6.3.2.
* Test to make sure it looks good - nothing was missed
* Put the 6.3.2 module on vasl.info
* Put announcements on GS and Facebook. The release notes are on vasl.info - they probably need to be cleaned up a bit. 
* Merge the 6.3 branch into develop
* Play a lot more VASL in the coming months.

**Comment by davidsullivan317** [comment] 2016-03-05 19:26
I fixed a bunch of the outstanding small bugs. Here is a link to the 6.3 release candidate. 
https://www.dropbox.com/s/n5q60ibuh14x7rw/vasl-6.3.2.vmod?dl=0

If folks would please give it a look - run through the changes that are in 6.3 - I'd appreciate it.

**Comment by derimmer** [comment] 2016-03-07 18:06
Hi Sully

 

Did not check everything but can confirm that automatic board updating is working. 

 

Plus, the overlay stuff that I did seems to be fine.

 

I did notice that whenever a board is cropped, LOS checking is disabled. Is this what is supposed to happen?

 

Doug

**Comment by mistertakai** [comment] 2016-03-09 21:30
I'm using the version to do my logs, so far no problems. I did crop a board and tried LoS checking, it did work, but does not display blocked LOS. I remember that this doesn't work with every board, as it requires LOS data, I tried a couple. Which board would I use to test it?

**Comment by davidsullivan317** [comment] 2016-03-19 19:04
I'm able to recreate cropping errors only when the board configuration is changed after starting play. If I create a new game with cropped boards it works fine. If I save and reopen a game with copped boards it works fine. If I create a new game with cropped boards and then update the board configuration I get the error. I know what the problem is and will open a new bug for this to fix in a later release.

Let me know if that's not consistent with the errors you are seeing.

**Comment by davidsullivan317** [comment] 2016-03-19 20:02
Here's the final release of 6.3: https://www.dropbox.com/s/75ywrskhkeg9f4k/vasl-6.3.3.vmod?dl=0

Sam - can you upload it vasl.info?

**Closed** 2016-03-26 14:42 UTC
Labels: 2 - Code, Discussion
