### ISSUE TITLE
Clean up dist folder

### ISSUE THREAD

**Issue by styson** [vasl-developers/vasl#646] opened 2020-04-17 16:31 UTC
**These images are here, but are also in the correct nationality folders:**

Finnish:
fi120MTR.png
fi20L4.png
fi20L6.png
fi25LLAT.png
fi37LAT H.png
fi37LAT.png
fi45LAT.png
fi50LAT.png
fi7.62AA.png
fi75LAT.png
fi76ART.png
fi76INF.png
fi81mmMTR Savu.png
fi81mmMTR.png
fiAA76L.png
fiAA76LB.png
fiAA76LBmalf.png
fiT-50r.png

Allied:
FT17C.gif

British:
morris.gif

**This Hungarian crew should be in hu:**
hu126C.png

**These Russian images are in dist, but not in ru/veh:**
Lee(a)RU.gif
RU VALV.gif
RU VALVnoaa.gif
ruM3A1 SC UA.gif
ruM3A1 SCB.png

This is duplicated elsewhere  (other folder):
_brownd58.gif                   (ML)

These should be moved to MS:
Tunnel1.png
Tunnel2.png
Tunnel3.png
SawTunnelUsed.gif
UpperEncircled.gif

**Comment by derimmer** [comment] 2020-04-17 17:53
Sam, this is super helpful. Great job. We should move these images to the right places and eliminate the duplicates. Please note however, that moving the images will break the counters. So the counters have to be fixed right after the move. 

I am in the middle of fixing the broken counters that Brian found which was also very helpful. We should do this in two phases to avoid overwriting changes in the buildFile. I will finish my counter fixes and push  the changes to github and then we can work on these. Many thanks.

**Comment by derimmer** [comment] 2020-10-26 22:36
I have reviewed the fi counters on Sam's list. In all but one case, it appears to me that the version in the images directory is the one currently in use and updates the counter mostly by making the white circle background of the M # more visible. 

In these cases, I think the appropriate action is to move the revised .png to the images\fi\gun folder and then reset the counters to use these images in their new location. I can certainly do all of this.

Does any one recall the history of these finish gun counters. was there a need to update them?

The one image that doesn't fit this bill is fiAA76LBmalf. The purpose of this image is to show the malf X on the reverse side of the counter as distinguished from fiAA76LB which shows the 76 AA gun in limbered mode. In my view this image needs to be moved to the images\fi\gun folder and added to the Layer trait in the counter. Any issues with that. 

I am not a counter guy so I would appreciate some advise as to whether or not this makes sense.

**Comment by BigAl737** [comment] 2020-10-27 04:20
Hi Doug. Thought I'd have time tonight to check this for you, but no. Give me one more day and I'll have an answer for you. Thanks.

**Comment by derimmer** [comment] 2020-10-27 12:24
No rush. I will wait until I hear from you. Thanks muchly. 

Doug

**Comment by BigAl737** [comment] 2020-10-27 18:58
I've taken a look at fiAA76LBmalf and can make the fix. I'll also be updating the Lee(a)RU counter to add a white dot to the BMG. It looks like you may be working on the build file now so I'll wait till tonight.

**Comment by derimmer** [comment] 2020-10-27 19:16
Go ahead whenever Al. I will not be working on this today. I will wait until I see your changes to the buildFile go up to github. 

 

Doug

 

Thanks for the help!

**Comment by BigAl737** [comment] 2020-10-27 19:23
Looking at all the fi Guns and I've found that they handle the malf layer different than standard. They work as is but it's not ideal in my opinion. The counter graphics of all the fi counters could be improved for clarity as well. Like a house project, a simple fix could grow into a time consuming undertaking. My thought is that you can delete the fiAA76LBmalf counter. It's not being used as far as I can tell. I'll make the change to the Lee counter and then you're free to move all the counters in Sam's list as you deem best. I can help fix anything that gets broken because of the clean up. Eventually, I can update all the fi counters to standard.

**Comment by BigAl737** [comment] 2020-10-27 19:32
The Lee counter has been updated Doug. You're free to do the voodoo that you do so well.

**Comment by derimmer** [comment] 2020-10-27 19:48
Agreed.

**Comment by derimmer** [comment] 2020-10-28 03:05
I have moved the counters from the images file into fi/gun and assigned them to the counters. Everything is looking good. However, in checking the results against images in my hardcopy of Chapter H, I see what appear to be three errors. I have verified that these same errors appear in vasl6.5.1 so I don't think they were caused by my changes. Pre-existing conditions to be sure.

33. 20 ItK/30 BSW(g) this is a 20L(4) AA gun. It is missing its Limbered layer on the counter and there is no image for the limbered gun in fi/gun.

34. 20 ItK/38 BSW(g) this is a 20L(6) AA gun. It is missing its Limbered layer on the counter but there is an image for the limbered gun in fi/gun. The image for the non-limbered version has B11 which is not found on the image in my Chapter H.

35. 20 ItK/35 Br this is a 20L(4) AA gun. The non-limbered image has B11 which is not found on the image in my Chapter H. 

I will mark this part of dist cleanup as done. And will create 2 new issues, one to deal with these 3 counter errors and one to deal with the improvement of the counter graphics for the Finns in general.

**Comment by derimmer** [comment] 2020-10-28 14:31
@BigAl737 can you post or email me the Lee counter gif. I think I have gotten something mixed up.

**Comment by derimmer** [comment] 2020-10-28 14:44
I am loath to touch _brownd58.gif as I can't find where it shows up in the counter palette. Anyone?

Plus, the UpperEncircled gif exists but I can't find that counter either?

**Comment by BigAl737** [comment] 2020-10-28 17:25
![Lee(a)RU](https://user-images.githubusercontent.com/10384413/97473161-890d2800-18ff-11eb-86b3-df447561af0f.gif)

**Comment by derimmer** [comment] 2020-10-28 17:28
My Russian colored Lee counter (cardboard version) also has an asterisk beside the AAMG in addition to the 3 that you have on this counter. 

Not sure which is correct?

**Comment by BigAl737** [comment] 2020-10-28 17:58
The cardboard version. There's actually 4 "*" on the cardboard version...one by the ROF box, one by the B75, one by the 37LL, and one by the aamg. The British colored version is wrong too. I've have a fix for both posted here shortly.

**Comment by BigAl737** [comment] 2020-10-28 18:20
lee2.gif
![lee2](https://user-images.githubusercontent.com/10384413/97478546-f459f880-1905-11eb-8e55-510024d9ada8.gif)

lee.gif
![lee](https://user-images.githubusercontent.com/10384413/97478558-f8861600-1905-11eb-9295-556ea4a7269c.gif)

grant.gif
![grant](https://user-images.githubusercontent.com/10384413/97478574-fcb23380-1905-11eb-9cee-e722bf44c591.gif)

Lee(a)RU.gif
![Lee(a)RU](https://user-images.githubusercontent.com/10384413/97479500-29b31600-1907-11eb-8b7c-9d9ca3c409bf.gif)

Sent you an email with a quick question if you have time to answer before I push these to images. Or you can push these if you'd prefer.

**Comment by derimmer** [comment] 2020-10-28 20:18
I will push these up as I need to add them to my module, test it, and then push the changes along with other dist cleanup changes to github. No worries. I have the Russian vehicles working except for the Lee counter.  I seem to have made a mess of the Tunnel counters though. Will keep me busy for another day! Thanks for your help on this.

**Comment by derimmer** [comment] 2020-10-29 22:11
This is now done and I am going to close the issue. Great work by Sam to get us started on this. I was able to make every change except moving the _brownd58.gif as I could not figure out where it was used. One stray does not seem so bad.

@styson @BigAl737 If you look in the Russian/LeadLease/Lee(a) tab you will see 4 counters (if you have the BFP extension loaded) 2 British and 2 Russian. One of the Russian counters has all 4 *. The other, which comes from the BFP extension (I have verified this) is missing one.  Over to you.

**Closed by derimmer** 2020-10-29 22:11 UTC
Labels: 1 - Counters
