### ISSUE TITLE
Update RB VASL board

### ISSUE THREAD

**Issue by BigAl737** [vasl-developers/vasl#565] opened 2019-05-13 22:01 UTC

**Comment by BigAl737** [comment] 2019-09-16 04:41
What do you think of this for a ground snow look?

![image](https://user-images.githubusercontent.com/10384413/64934705-0c051900-d7f9-11e9-8f09-b3202c317015.png)

**Comment by zgrose** [comment] 2019-09-16 13:42
Doesn't say Snow to me, but I like the direction you're taking.

**Comment by BigAl737** [comment] 2019-09-17 05:07
More subtle blotching. Better?

![image](https://user-images.githubusercontent.com/10384413/65013004-d67a3180-d8c5-11e9-883d-976831c37d0e.png)

**Comment by hongkongwargamer** [comment] 2019-09-17 05:44
I just took a look against RBv3.  I like the LESS subtle blotching version (the first one).  That to me articulates the "not-nice-and-neat" winter scene amongst the rubble.  

The bottom version looks like a faded RBv3 map.  Thx

**Comment by zgrose** [comment] 2019-09-17 14:11
Concur with @hongkongwargamer. I think you need more white, not less.
Random non-ASL example: http://www.gmtgames.com/redwinter/RWFinalMapCloseup.jpg
Less random ASL example: 
![image](https://user-images.githubusercontent.com/5044847/65049239-0e679000-d92b-11e9-8e72-08c0b8c46dd7.png)

**Comment by BigAl737** [comment] 2019-09-18 19:02
Snow on shredded earth while maintaining enough definition to make out the terrain elevations?

![image](https://user-images.githubusercontent.com/10384413/65177679-a9339d80-da03-11e9-9776-fc539cd0bf55.png)

**Comment by zgrose** [comment] 2019-09-18 20:28
Yes, way better than both previous versions.
Since there are only 2 elevations, IIRC, you can probably even make Level One (which dominates the map) whiter since you only need to know where the Level Zero is located.

**Comment by hongkongwargamer** [comment] 2019-09-18 22:37
Agreed!!!  This is brilliant.  

Once thing - I don't know what it's like to be color blind but there seems to be more color blind people than there are lefties.  Might want to see if they can make out the distinction.

**Comment by BigAl737** [comment] 2019-09-18 23:24
Thanks guys. Last one...a larger sample this time. Click on it to make it full size.

A little less chicken poxy. Better? Worse? Ready to go final?

![image](https://user-images.githubusercontent.com/10384413/65193556-fc1f4c00-da27-11e9-9154-7e86c0f0c3b0.png)

**Comment by hongkongwargamer** [comment] 2019-09-18 23:50
Personally I love it.

**Comment by zgrose** [comment] 2019-09-19 00:02
Well, your sample size of 2 are fans. :) The real test will be the unwashed masses on GameSquad.

**Comment by bkemp01** [comment] 2019-09-19 02:03
that last one’s a winner for me, nice work Al

**Comment by BigAl737** [comment] 2019-09-19 02:30
I’d say 100% satisfaction is good enough :-)

Thanks guys. Much appreciated.

**Comment by BigAl737** [comment] 2019-10-22 20:21
Please see top post for update.

**Comment by derimmer** [comment] 2021-02-03 16:09
Hi I have got los working on the latest version of RBv3 that Al has given me. It would help if some folks could take it for a test drive and let me know if I missed anything. The HASL maps take a bit of handcrafting in the los-gui program so I might have missed one or two things. Get it here. Unzip it and put it in your boards folder. It will not be overwritten by autosyncing as I have bumped the version number. 

[https://www.dropbox.com/s/l5jtlpnojhonope/bdRBv3.zip?dl=0](url)

@BigAl737 feel free to post this on GS or I can do it?

Working on RO now.

**Comment by derimmer** [comment] 2021-02-03 16:19
Link to the VASL6.6.2-beta2.vmod. Which requires VASSAL3.5.0. Use it to test RBv3

[https://www.dropbox.com/s/525cpitlx5x66w5/vasl-6.6.2-beta2.zip?dl=0](url)

**Comment by Javaslinger** [comment] 2021-02-03 17:35
I'm not sure if this is normal, but when inside a building, I think it's counting too many hinderances for debris.  Whereas outside of a building it seems to be working correctly.  For example, L16 to L19 shows range 3 with 4 Hinderances.

**Comment by derimmer** [comment] 2021-02-03 18:03
> I'm not sure if this is normal, but when inside a building, I think it's counting too many hinderances for debris. Whereas outside of a building it seems to be working correctly. For example, L16 to L19 shows range 3 with 4 Hinderances.

My understanding is that debris in Roofless Factory hexes is added to the Factory Hindrance for a net +2 per hex. But only for Roofless Factory hexes. See RB5.41. Do you see any cases where a Roofed Factory hex is showing +2 Hindrances?

**Comment by Javaslinger** [comment] 2021-02-03 18:09
Well, there ya go.  The issue is not with the map, but with my lack of understanding roofless factory rules....  They are working correctly.

**Comment by BigAl737** [comment] 2021-02-04 20:52
I always wondered what to do in situations like this...

![image](https://user-images.githubusercontent.com/10384413/106953289-ab70c780-66de-11eb-93cb-148ff917e794.png)

This was the very first LOS I checked and it looks like it should work as the R10 factory is not visible on both sides of the thread. I'm sure there's tons of examples like this. It's not helped by the start of the thread in Q11 being a pixel high and left of center. This positioning is not consistent through out the map however because the VASL hexgrid is not consistent.

I could check this LOS on my paper map but it may give a different result than your paper map.

Let me know if situations like this are a consistent problem and I could make adjustments on an individual basis.

**Comment by derimmer** [comment] 2021-02-04 21:08
VASL los does not look for obstacles on both sides of the line. If it hits an obstacle, los is blocked. So in your case the los is "working" as it was programmed to do.

(1) In situations like this players can use their eyeballs and discretion and say, no, we are going to play that as clear. Or not.
(2) As we have discussed in the past, it would be possible to program the los engine to grab the 8 adjacent pixels and check them for the obstacle. Then you would have to do some logic with the slope of the los line to determine if the obstacle was present on both sides of the line. Doable, but . . . .  

I have a couple of important los bugs to do first as there is still too much freezing going on. I have fixed one cause but there are others out there! 

I will create this as an issue to remind us.

**Comment by BigAl737** [comment] 2021-02-04 21:34
Thanks Doug. Leaving it to the players is a good option.

One thing I considered when I was making the LOS map image for you was shrinking the obstacle footprint by one pixel so cases like this would look more blocked. I didn't do that but that is an option.

**Comment by derimmer** [comment] 2021-02-16 20:01
Have finally got RO los working (and RF as well). See RO thread #564 for access to necessary files for testing, which I would appreciate.

**Closed** 2021-05-07 19:29 UTC
Labels: 0 - Boards, enhancement
