### ISSUE TITLE
Fix deprecated VASSAL methods, etc

### ISSUE THREAD

**Issue by derimmer** [vasl-developers/vasl#764] opened 2020-10-14 21:51 UTC

**Comment by derimmer** [comment] 2020-10-21 19:05
@uckelman @BigAl737 @zgrose @bkemp01 @jrvjrv 

I am working on replacing all of the VASL code that uses deprecated VASSAL methods that will eventually be removed from VASSAL. I hope to have this complete for VASL6.6.2 next spring. Some are straightforward; others are not. 

Here is a not straightforward one.

VASL.build.module.map.boardpicker.overlay.java has a method that uses deprecated VASSAL code:

![overlaysnipdep](https://user-images.githubusercontent.com/7696161/96770746-bb260380-13ae-11eb-8e23-f13d722e6c11.PNG)

In VASSAL, the method, in DataArchive.java, looks like this:

![vassaldep1](https://user-images.githubusercontent.com/7696161/96769769-8f564e00-13ad-11eb-951d-b5d9e63c2a87.PNG)

If I am reading this correctly we can choose from two methods. What's a boy to do? 

I remember that Al started a discussion issue (#627 ) about using svg images.  These methods seem exclusive, either we use svg or not. Doesn't feel to me like we can have both? Am I right?

**Comment by uckelman** [comment] 2020-10-21 19:12
No, you shouldn't use either of those---`getImageInputStream()` is also deprecated. You should be using `Op.load()` to get an `ImageOp` for the image from the `DataArchive`. `ImageOp.getSize()` will tell you the size of the image.

**Comment by uckelman** [comment] 2020-10-21 19:15
To be clear, the reason the advice in the deprecation notice doesn't apply is that you shouldn't be using `getImageSize()` here in the first place---the advice is applicable only in places where that was the right thing to begin with.

**Comment by derimmer** [comment] 2020-10-21 19:25
> No, you shouldn't use either of those---`getImageInputStream()` is also deprecated. You should be using `Op.load()` to get an `ImageOp` for the image from the `DataArchive`. `ImageOp.getSize()` will tell you the size of the image.

There is a replacement for getImageInputSteam() identified in VASSAL: getInputStream().

There is another deprecated method in VASSAL.DataArchive used in VASSAL and that is getImageSize, used in VASL....Underlay.java

I am slowly going crazy, 1, 2, 3, 4, 5, 6, switch, crazy going slowly am I, 6, 5, 4, 3, 2, 1, switch. LOL.

So, we need to rework VASL classes Overlay, Underlay, and SSROverlay to use VASSAL class Op?

**Comment by uckelman** [comment] 2020-10-21 19:33
The image loading changes aren't new---they're from VASSAL _3.2_, which was released in 2012. 

Using `getInputStream()` means that you're avoiding VASSAL's image caching. There are sometimes reasons to do this, but anything which is drawing onto a map should be getting its images via an `ImageOp`.

**Comment by uckelman** [comment] 2020-10-21 19:43
What you need in `Overlay` is to have `image` be an `ImageOp` member rather than an `Image`.
Assign to it in your ctor: `image = Op.load(nameofimage);` Then you can return `image.getImage()` from `getImage()`, or just remove it if no subclasses use it. You can remove `loadImage()`. In `setBounds()` , you call `image.getSize()` instead of what you're doing now. If you change the image name (it looks like the name depends on the orientation?), you just do `image = Op.load(newimagename)` to reset it.

**Comment by uckelman** [comment] 2020-10-21 19:45
There are a _lot_ of examples of this kind of thing if you look though VASSAL's code. There are also some in VASL already.

**Comment by uckelman** [comment] 2020-10-21 20:05
The general rule here is that you should not store an `Image` or `BufferedImage` which VASSAL could cache, but instead get it from `ImageOp.getImage()` at the point where you use it.

**Comment by derimmer** [comment] 2020-10-21 20:29
I appreciate the help as always. I have time to get this right. Thanks.

**Comment by uckelman** [comment] 2020-10-21 20:32
If you show me what you're doing as you go, I'm happy to comment.

**Comment by derimmer** [comment] 2020-10-25 18:05
@uckelman I have this mostly working in Overlay. One problem:

The following two lines of code (the new and the old) return different sizes. The old code returns the size of the .gif file. The new code appears to return the size of the part of the image that contains non-transparent pixels. Most of our overlays contain large amounts of transparent pixels. Is this likely? I can find no other explanation. 

boundaries.setSize(image.getSize());
boundaries.setSize(archive.getImageSize(fileName(name + c)));

For example, overlay g1 has a size of 225,194, but image.GetSize() returns 84, 74

The impact of this is that the image is not placed properly as proceeding code generates the top left position of the overlay - based on the file size as best as I can determine. Overlay.getDefaultOriginList appears central to this. 

If it were a case of knowing the hex centre point and then centering the image around that point, then it would be easy. The reason for the convolutions in Overlay is that the overlays are not placed based on their centre points; the alignment is more complex which Overlay manages. 

Can we return the full image size including transparent pixels? I could not find a method in ImageOp that appeared to do so.

**Comment by uckelman** [comment] 2020-10-25 22:55
I'll have a look sometime this week. Cutting out transparent pixels doesn't sound like something we do normally---I certainly don't recall writing any code to do that.

**Comment by derimmer** [comment] 2020-10-26 19:19
Thinking about this some more. The two methods, image.getSize() and archive.getImageSize() are perhaps getting the image in different ways that is resulting in a different size. 

For image = Op.load(), when I break on that line, I see the following variables:

![deprecatesnip1](https://user-images.githubusercontent.com/7696161/97213420-f8680800-1797-11eb-9883-629efc538ead.PNG)

ovrg1a.gif is not stored in the directory "C:\users\ . . . \overlays." Rather, it is stored along with other images in a zipfile named ovrG, which is in the \overlays directory. Somehow, image is being assigned the ovrg1a.gif in the constructor (I have looked at what Op.load() does. It appears to go to SourcOpBitmapImpl and then set a hash value. I don't understand this). When I test using image.getImage in the constructor, I can see the image correctly but is is clearly cut to include only rows and columns of pixels with non-transparent pixels.

For archive.getImageSize(), when I break on that line, it is looking inside "archive" which is a variable holding the ovrG zipfile and returns the full image.

![deprecatesnip2](https://user-images.githubusercontent.com/7696161/97213435-fe5de900-1797-11eb-854c-46e34a99bd81.PNG)

I suspect that the zipfile is effecting the Op.load() in the constructor and that is then causing the problem? But this is new stuff to me so I am only guessing.

**Comment by uckelman** [comment] 2020-10-27 14:49
I see what the problem is in Overlay: It looks like you're reading the overlay images _from a file which isn't the module file_. I hadn't known you were doing that. This is going to require some thought about how to proceed. I may need to make some additions to how image loading works in VASSAL to accommodate this. My recommendation is to work on other things in the meantime.

**Comment by derimmer** [comment] 2020-10-27 15:29
OK. All of our map images are loaded this way from external files as are the overlays. Our counter images are loaded from within the module. Some counter images are loaded from extensions but I assume that is the same as from within the module.

**Comment by derimmer** [comment] 2020-12-15 14:28
@uckelman I would like to come back to this if we can. I am planning to release VASL6.6.2 in April/May 2021 and would like to have all the deprecated code issues resolved. As well, I would anticipate building 6.6.2 with VASSAL3.5.X. A couple of questions:

1. Is there a good time for you in the Jan-Mar 2021 window to work on the image loading issue discussed in this thread?
2. Do you have a guesstimate of when VASSAL3.5.0 will be officially released? If it is likely before my timeline for VASL6.6.2 then I will move my development environment to use 3.5.0-beta.

**Comment by uckelman** [comment] 2021-01-21 20:38
>     2. Do you have a guesstimate of when VASSAL3.5.0 will be officially released?

We'll release 3.5.0 by the end of January.

**Comment by uckelman** [comment] 2021-01-21 20:48
```
WARNING] /home/uckelman/projects/VASSAL/VASL/vasl/src/VASL/build/module/map/boardPicker/ASLBoard.java:[132,24] dataError(VASSAL.build.BadDataReport) in VASSAL.tools.ErrorDialog has been deprecated
```
`ErrorDialog.dataError` is `ErrorDialog.dataWarning` now.

**Comment by uckelman** [comment] 2021-01-21 20:53
```
[WARNING] /home/uckelman/projects/VASSAL/VASL/vasl/src/VASL/counters/Turreted.java:[115,19] getCurrentImage() in VASSAL.counters.Embellishment0 has been deprecated and marked for removal
```
Nothing I can see in the current code uses `Turreted.getCurrentImage()`. I suggest deprecating or removing it.

**Comment by derimmer** [comment] 2021-01-21 20:58
> > ```
> > 2. Do you have a guesstimate of when VASSAL3.5.0 will be officially released?
> > ```
> 
> We'll release 3.5.0 by the end of January.

Super. I have already built VASL using the 3.5.0-beta2 so I don't anticipate any problems using 3.5.0 for the official release of VASL6.6.2. I suspect it will be around March/April.

Do you anticipate the same vigorous release schedule for VASSAL 3.5.0 and beyond as we had for VASSAL3.4.X?

**Comment by uckelman** [comment] 2021-01-21 21:02
> Do you anticipate the same vigorous release schedule for VASSAL 3.5.0 and beyond as we had for VASSAL3.4.X?

We'll be fixing bugs as they arise with 3.5, but once it's released we're shifting the main effort to V4. Most of the work during 3.4 was fixing old bugs; I don't foresee much of that sort of work during 3.5.

**Comment by uckelman** [comment] 2021-01-21 21:31
```
[WARNING] /home/uckelman/projects/VASSAL/VASL/vasl/src/VASL/build/module/map/boardPicker/SSROverlay.java:[70,34] getImageInputStream(java.lang.String) in VASSAL.tools.DataArchive has been deprecated and marked for removal
```
I think using `archive.getInputStream(name)` instead of `archive.getImageInputStream(name)` will work here, as you're already calling `archive.getInputStream(name)` in the ctor---but I have not tested this.

**Comment by uckelman** [comment] 2021-01-21 21:51
```
[WARNING] /home/uckelman/projects/VASSAL/VASL/vasl/src/VASL/build/module/map/boardPicker/Overlay.java:[140,38] getImageInputStream(java.lang.String) in VASSAL.tools.DataArchive has been deprecated and marked for removal
```
Is it correct that overlay images are expected to be in the root directory of overlay archives? If that's so, then `archive.getInputStream(fileName(name + c))` should work here.

**Comment by uckelman** [comment] 2021-01-21 21:58
```
[WARNING] /home/uckelman/projects/VASSAL/VASL/vasl/src/VASL/build/module/map/boardPicker/Overlay.java:[192,35] getImageSize(java.lang.String) in VASSAL.tools.DataArchive has been deprecated and marked for removal
```
Instead:
```
final String fn = fileName(name + c);
try (InputStream in = archive.getInputStream(fn)) {
  boundaries.setSize(ImageUtils.getImageSize(fn, in));
}
```

**Comment by uckelman** [comment] 2021-01-21 22:10
```
[WARNING] /home/uckelman/projects/VASSAL/VASL/vasl/src/VASL/build/module/map/boardPicker/Underlay.java:[70,32] getImage(java.lang.String) in VASSAL.tools.DataArchive has been deprecated and marked for removal
```
This runs only if the first attempt at loading the underlay image fails. Does that ever happen? If so, is the second attempt ever actually successful?

**Comment by derimmer** [comment] 2021-01-21 22:49
Thanks for all of this @uckelman. I will test it out over the next few days and let you know. As you will have seen, we have a new coder in town (@mtl1971) and he clearly knows a lot more about this than me so I hope we can get all the deprecated stuff done pretty soon.

**Comment by mtl1971** [comment] 2021-01-21 23:01
> ```
> [WARNING] /home/uckelman/projects/VASSAL/VASL/vasl/src/VASL/counters/Turreted.java:[115,19] getCurrentImage() in VASSAL.counters.Embellishment0 has been deprecated and marked for removal
> ```
> 
> Nothing I can see in the current code uses `Turreted.getCurrentImage()`. I suggest deprecating or removing it.

I can't see anything using this either - a quick test with a bunch of vehicle counters never ended up in a call to it - so removing it is probably safe.

**Comment by mtl1971** [comment] 2021-01-21 23:27
Thanks, Mr. @uckelman - this is very helpful. I'll try to look at these tomorrow before beer-o'clock.

**Comment by mtl1971** [comment] 2021-01-22 11:07
Ok, - that's the VASSAL deprecated code updated.

**Comment by derimmer** [comment] 2021-01-22 16:30
> ```
> [WARNING] /home/uckelman/projects/VASSAL/VASL/vasl/src/VASL/build/module/map/boardPicker/Overlay.java:[140,38] getImageInputStream(java.lang.String) in VASSAL.tools.DataArchive has been deprecated and marked for removal
> ```
> 
> Is it correct that overlay images are expected to be in the root directory of overlay archives? If that's so, then `archive.getInputStream(fileName(name + c))` should work here.

See my response on the underlay question, but basically they should be in  userpath/boards/overlays. The individual images themselves are in zip files in this directory. The userpath/boards is stored as a preference and so userpath/boards/overlays can be generated in the code regardless of the actual userpath.

**Comment by mtl1971** [comment] 2021-01-23 13:35
> > ```
> > [WARNING] /home/uckelman/projects/VASSAL/VASL/vasl/src/VASL/build/module/map/boardPicker/Overlay.java:[140,38] getImageInputStream(java.lang.String) in VASSAL.tools.DataArchive has been deprecated and marked for removal
> > ```
> > 
> > 
> > Is it correct that overlay images are expected to be in the root directory of overlay archives? If that's so, then `archive.getInputStream(fileName(name + c))` should work here.
> 
> See my response on the underlay question, but basically they should be in userpath/boards/overlays. The individual images themselves are in zip files in this directory. The userpath/boards is stored as a preference and so userpath/boards/overlays can be generated in the code regardless of the actual userpath.

**Comment by derimmer** [comment] 2021-01-30 22:40
Morris, can we close this one now?

**Comment by mtl1971** [comment] 2021-01-31 07:55
Yes - it's done.

**Closed by mtl1971** 2021-01-31 07:55 UTC
Labels: 2 - Code

**Comment by derimmer** [comment] 2021-04-06 18:47
@mtl1971 In doing a build of VASL6.6.2-beta3 today with VASSAL3.5.4, I noticed a new deprecation message: 

/VASL/build/module/map/PieceLinker.java:[352,42] getKeyStrokeForEvent(java.awt.event.KeyEvent) in VASSAL.tools.NamedKeyStroke has been deprecated

Morris, you have done a great job on these so far. Could you take on this last one for us?

**Comment by mtl1971** [comment] 2021-04-06 18:55
No problem - I'll take a look now.

**Comment by uckelman** [comment] 2021-04-06 19:12
Replace with `NamedKeyStroke.of()`

**Comment by mtl1971** [comment] 2021-04-06 19:17
Thanks, Joel.

**Comment by mtl1971** [comment] 2021-04-06 19:25
All done:
https://github.com/vasl-developers/vasl/pull/897

**Comment by mtl1971** [comment] 2021-04-07 10:20
A few more on the way in VASSAL 3.5.5:

[WARNING] /D:/dev/vasl/src/VASL/build/module/map/ASLImageSaver.java:[35,11] launch in VASSAL.build.module.map.ImageSaver has been deprecated and marked for removal
[WARNING] /D:/dev/vasl/src/VASL/build/module/map/ASLImageSaver.java:[35,52] launch in VASSAL.build.module.map.ImageSaver has been deprecated and marked for removal
[WARNING] /D:/dev/vasl/src/VASL/build/module/map/ASLImageSaver.java:[48,36] launch in VASSAL.build.module.map.ImageSaver has been deprecated and marked for removal
[WARNING] /D:/dev/vasl/src/VASL/build/module/map/ASLImageSaver.java:[49,48] launch in VASSAL.build.module.map.ImageSaver has been deprecated and marked for removal
[WARNING] /D:/dev/vasl/src/VASL/build/module/map/ASLImageSaver.java:[51,9] launch in VASSAL.build.module.map.ImageSaver has been deprecated and marked for removal
[WARNING] /D:/dev/vasl/src/VASL/build/module/map/ASLImageSaver.java:[62,31] launch in VASSAL.build.module.map.ImageSaver has been deprecated and marked for removal
[WARNING] /D:/dev/vasl/src/VASL/build/module/map/ASLTextSaver.java:[34,32] launch in VASSAL.build.module.map.TextSaver has been deprecated and marked for removal
[WARNING] /D:/dev/vasl/src/VASL/build/module/map/ASLTextSaver.java:[45,44] launch in VASSAL.build.module.map.TextSaver has been deprecated and marked for removal
[WARNING] /D:/dev/vasl/src/VASL/build/module/map/ASLTextSaver.java:[55,30] launch in VASSAL.build.module.map.TextSaver has been deprecated and marked for removal

**Comment by mtl1971** [comment] 2021-04-07 11:16
Thanks - and done.
https://github.com/vasl-developers/vasl/pull/898

**Comment by mtl1971** [comment] 2021-04-07 11:18
@uckelman - are there any more changes in the pipeline for a 3.5.6 or is it just any bugs that might boil out of 3.5.5?

**Comment by uckelman** [comment] 2021-04-07 12:05
If there is a 3.5.6, it will be bug-fix only.

**Comment by derimmer** [comment] 2021-04-07 15:02
> Use `getLaunchButton()` to get the launch button instead.

@uckelman Can you remember what class this was in reference to? I hadn't noticed this.

**Comment by uckelman** [comment] 2021-04-07 15:05
`getLaunchButton()` is a method of `VASSAL.build.AbstractToolbarItem`, which is an ancestor of `VASSAL.build.module.map.ImageSaver` and `VASSAL.build.module.map.TextSaver`.

**Comment by mtl1971** [comment] 2021-04-07 15:46
@derimmer - from our end it was in ASLImageSaver.java and ASLTextSaver.java. I did a quick recompile of VASL with VASSAL 3.5.5 this morning and noticed that there was more code marked as deprecated with that version, which wasn't marked when compiling against 3.5.4.

**Comment by derimmer** [comment] 2021-04-07 15:48
OK. launchbutton is also used with the los thread and i just wanted to be sure there was no deprecation there. Thanks
