### ISSUE TITLE
Primosole Bridge map (PBR) hexes are mis-reporting

### ISSUE THREAD

**Issue by davidsullivan317** [vasl-developers/vasl#191] opened 2015-03-05 13:57 UTC
On the Primosole Bridge map the hex numbers for hexes in columns A, C, E, etc. are off by one. 

![pbr-sample](https://cloud.githubusercontent.com/assets/5281926/6505998/04fea1ea-c30d-11e4-9b1a-bbac8b226a97.jpg)

**Comment by BigAl737** [comment] 2015-03-29 06:17
The problem is alternate hex grain numbering is not in use. Also, this board hasn't been converted to Metadata. I've created a metadata file (pasted below) but still am getting an error. What's the proper syntax for "alternate=true" in metadata?

<?xml version="1.0"?>





-<boardMetadata height="28" width="25" alternate="true" boardImageFileName="bdPBR.gif" author="TR" versionDate="Mar 2015" version="1.1" name="PBR">





-<overlaySSRules>




</overlaySSRules>


-<colors>




</colors>


-<colorSSRules>




</colorSSRules>

</boardMetadata>

**Comment by davidsullivan317** [comment] 2015-03-29 13:56
Use: altHexGrain="true"

Note that this code has never been used before so you'll have to test carefully.

**Comment by BigAl737** [comment] 2015-03-29 22:59
It seems I have a working metadata file but still recognition of the alternate hex grain. I've attached what I've got so far. If you have time, please check to see if I'm overlooking something obvious. Thanks. Hmmm, can't attach a zip file. I'll email it to you.

**Comment by davidsullivan317** [comment] 2015-03-30 01:08
Looks like there's a bug if there's no data file in the archive. I've fixed it and a new build is available here: https://www.dropbox.com/s/ftweppp8jqrqx5i/vasl-6.3.0-Snapshot-20150329.vmod?dl=0

Also note that you have to set the location of A1 center dot on this map;

<boardMetadata 
	name="PBR" 
	version="1.1" 
	versionDate="Mar 2015" 
	author="TR" 
	boardImageFileName="bdPBR.gif" 
	hasHills="FALSE" 
	width="25" 
	height="28" 
	A1CenterX = "1"
	A1CenterY = "98"
	altHexGrain="true">

**Comment by BigAl737** [comment] 2015-03-30 05:19
Thanks David,

Got the hex row ID issue fixed but the LOS string is off 8 pixels at the bottom of the map. What’s the metadata syntax to define dx and dy?

Al

**Comment by davidsullivan317** [comment] 2015-03-30 12:59
The syntax for dx and dy are:

	A1CenterX = "1"
	A1CenterY = "98"

It looks like the map uses a custom hex size. You'll have to figure this out by doing a little arithmetic with the image. Then use the following in the metadata:

	hexHeight = "x.x"
	hexWidth = "x.x"

Fiddle around with these 4 values until everything lines up.

**Comment by BigAl737** [comment] 2015-03-30 14:49
This issue is fixed. Thanks for your help David. Doesn't look like the PBR board has a home in src so I won't commit it. Let me know where to send it and we can close this issue.

**Comment by davidsullivan317** [comment] 2015-03-30 14:51
Do you want to try adding it to Github? Just create a folder in boards/src and add all of the files in the archive. You got this!

**Comment by BigAl737** [comment] 2015-03-30 15:31
Done?

**Closed** 2015-03-30 16:11 UTC
Labels: bug

**Comment by BigAl737** [comment] 2015-03-30 16:18
Done!
