### ISSUE TITLE
Add Transformation Orchards to Olive Groves

### ISSUE THREAD

**Issue by cscottk** [vasl-developers/vasl#1562] opened 2023-10-25 16:08 UTC
Low priority, but are we able to have a transformation of Orchards to Olive Groves?

**Comment by derimmer** [comment] 2024-03-31 13:26
This came up again in early 2024. The issue is that we don't have an Olive Groves terrain pattern.

It is also duplicated by #1638 so I am closing

**Closed by derimmer** 2024-03-31 13:26 UTC
Labels: enhancement
